import "./globals.css";
import { createBrowserClient } from "@/utils/supabase/client";
import { SupabaseProvider } from "@/utils/supabase/provider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "TheTronicvaultt",
  description: "Generated by create next app",

  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>{children}</SupabaseProvider>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
          }}
        />
      </body>
    </html>
  );
}
